2H-store-django/accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.profile, name='profile')
]

2H-store-django/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

2H-store-django/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

2H-store-django/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

2H-store-django/store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

2H-store-django/accounts/models.py
from django.db import models

# Create your models here.

2H-store-django/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.forms import modelform_factory, widgets
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

# Create your views here.


class Register(SuccessMessageMixin, generic.CreateView):
    form_class = UserCreationForm
    success_message = "Registration Successfull you can now login."
    template_name = "registration/register.html"
    success_url = reverse_lazy('login')


@login_required
def profile(req):
    UserEditForm = modelform_factory(
        get_user_model(), fields=('first_name', 'last_name', 'username'))
    form = UserEditForm(instance=req.user)
    if req.method == "POST":
        form = UserEditForm(instance=req.user, data=req.POST)
        if form.is_valid():
            form.save()
    return render(req, 'registration/profile.html', {'form': form})

2H-store-django/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
        <a href="#" class="navbar-brand">H&H Thời trang nam</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{% url 'store:product_list' %}" class="nav-link">
                <i class="fa fa-shopping-bag fa-lg mr-1"></i> Cửa hàng
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'store:categories_list' %}" class="nav-link">
                <i class="fa fa-shopping-basket fa-lg mr-1"></i> Thể loại
              </a>
            </li>
          </ul>
          <form action="/" class="inline-form mr-md-2 ml-auto">
            <div class="input-group">
              <input
                required
                type="text"
                name="name"
                placeholder="Tìm kiếm"
                class="form-control"
              />
              <div class="input-group-append">
                <button type="submit" class="btn-success btn btn-sm">
                  <i class="fa fa-search fa-lg"></i>
                </button>
              </div>
            </div>
          </form>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'orders:my' %}" class="nav-link">
                <i class="fa fa-truck fa-lg mr-1"></i> Đơn hàng
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cart:cart_details' %}" class="nav-link">
                <i class="fa fa-shopping-cart fa-lg"></i>
                <span class="badge badge-secondary">
                  {% if cart %} {{cart|length}} {% else %} 0 {% endif%}
                </span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle mb-0"
                data-toggle="dropdown"
              >
                {{request.user}}
              </a>
              <div class="dropdown-menu">
                <a href="{% url 'profile'%}" class="dropdown-item">Thông tin cá nhân</a>
                <a href="{% url 'password_change'%}" class="dropdown-item">
                  Đổi mật khẩu
                </a>
                <a href="{% url 'logout' %}" class="dropdown-item">đăng xuất</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">
                <i class="fa fa-sign-in fa-lg"></i> Đăng nhập
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">
                <i class="fa fa-user-plus fa-lg"></i> Đăng ký
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% if messages %}
      <div class="alert alert-success my-2">
        {% for message in messages %} {{message}} {% endfor %}
      </div>
      {% endif %} {% block content %} {% endblock content %}
    </div>
  </body>
</html>