2H-store-django/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

2H-store-django/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

2H-store-django/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

2H-store-django/store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

2H-store-django/cart/models.py
from django.db import models

# Create your models here.

2H-store-django/cart/forms.py
from django import forms


class CartForm(forms.Form):
    product_id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    quantity = forms.IntegerField(
        min_value=1, required=True, widget=forms.NumberInput({'class': 'form-control', 'value': 1}))

2H-store-django/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from cart.cart import Cart
from store.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from cart.forms import CartForm
# Create your views here.


@login_required
@require_POST
def add_to_cart(request):
    cart = Cart(request)
    form = CartForm(request.POST)
    if form.is_valid():
        product_id = form.cleaned_data['product_id']
        quantity = form.cleaned_data['quantity']
        product = get_object_or_404(Product, id=product_id, availibility=True)
        cart.add(product_id, product.price, quantity)
        messages.success(request, f'{product.name} added to cart.')
    return redirect('cart:cart_details')


@login_required
def cart_details(request):
    cart = Cart(request)
    products = Product.objects.filter(pk__in=cart.cart.keys())

    def map_function(p):
        pid = str(p.id)
        q = cart.cart[pid]['quantity']
        return {'product': p, 'quantity': q, 'total': p.price*q, 'form': CartForm(initial={'quantity': q, 'product_id': pid})}

    cart_items = map(map_function, products)
    return render(request, 'cart/cart_details.html', {'cart_items': cart_items, 'total': cart.get_total_price()})


@login_required
def remove_from_cart(request, id):
    cart = Cart(request)
    cart.remove(str(id))
    return redirect('cart:cart_details')


@login_required
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_details')

2H-store-django/cart/templates/cart/cart_details.html
{% extends 'base.html' %} {% block title %} Cart {% endblock title %}
{% block content %}
<h1 class="display-4 mt-4 text-center">Giỏ hàng</h1>
<hr />
{% if total %}
<div class="row justify-content-center">
  <div class="col-auto">
    <table class="table table-borderless table-striped table-responsive">
      <thead class="thead-dark">
        <tr>
          <th>Tên</th>
          <th>Đơn Giá</th>
          <th>Só lượng</th>
          <th>Xóa</th>
          <th>Tổng tiền</th>
        </tr>
      </thead>
      <tbody>
        {% for i in cart_items %}
        <tr>
          <td>
            <a href="{{i.product.get_absolute_url}}"> {{i.product.name}} </a>
          </td>
          <td>{{i.product.price}}VNĐ</td>
          <td>
            <form
              action="{% url 'cart:add' %}"
              class="form-inline"
              method="POST"
            >
              {% csrf_token %}
              {{i.form.product_id}}
              <div class="input-group">
                {{i.form.quantity}}
                <div class="input-group-append">
                  <button class="btn btn-primary btn-sm" type="submit">
                    <i class="fa fa-shopping-cart mr-1"></i> Chỉnh sửa
                  </button>
                </div>
              </div>
            </form>
          </td>
          <td>
            <a
              href="{% url 'cart:remove' i.product.id %}"
              class="btn btn-danger btn-sm"
            >
              <i class="fa fa-times mr-1"></i> Xóa
            </a>
          </td>
          <td>{{i.total}}VNĐ</td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot class="table-secondary">
        <tr>
          <td colspan="3"></td>
          <td>Tổng tiền -</td>
          <td><b>{{total}}VNĐ</b></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<div class="text-center">
  <a href="{% url 'cart:clear' %}" class="btn btn-warning">Làm sạch giỏ</a>
  <a href="{% url 'orders:place' %}" class="btn btn-success">Thanh Toán</a>
</div>
{% else %}
<div class="text-center">
  <h3 class="font-weight-light">Giỏ hàng trống</h3>
  <a href="{% url 'store:product_list' %}" class="btn btn-secondary">
    Trở lại cửa hàng
  </a>
</div>
{% endif %}
<script>
  let inputs = document.querySelectorAll("input.form-control");
  inputs.forEach((i) => i.classList.add("form-control-sm"));
</script>
{% endblock content %}