2H-store-django/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

2H-store-django/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

2H-store-django/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

2H-store-django/store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

2H-store-django/orders/models.py
from django.db import models
from django.conf import settings
from store.models import Product
from django.shortcuts import reverse

# Create your models here.

choices = (
    ('Pending', 'Pending'),
    ('Packed', 'Packed'),
    ('Shipped', 'Shipped'),
    ('Delivered', 'Delivered')
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='orders', on_delete=models.CASCADE)
    address = models.CharField(max_length=150, blank=False, null=False)
    pin_code = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        choices=choices, max_length=10, default='Pending')
    total_price = models.FloatField(null=False, blank=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_absolute_url(self):
        return reverse('orders:invoice', kwargs={'pk': self.pk})


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='ordered', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total = models.FloatField(null=False, blank=False)

    def __str__(self):
        return f'Order Item {self.id}'

2H-store-django/orders/forms.py
from orders.models import Order
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'city', 'pin_code']

2H-store-django/orders/views.py
from django.shortcuts import render, redirect, Http404
from django.views import generic
from orders.forms import OrderForm
from orders.models import Order, OrderItem
from cart.cart import Cart
from django.db.models import Count
from store.models import Product
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class CreateOrder(LoginRequiredMixin, generic.CreateView):
    form_class = OrderForm
    template_name = 'orders/place_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        products = Product.objects.filter(pk__in=cart.cart.keys())
        cart_items = map(
            lambda p: {'product': p, 'quantity': cart.cart[str(p.id)]['quantity'], 'total': p.price*cart.cart[str(p.id)]['quantity']}, products)
        context['summary'] = cart_items
        return context

    def form_valid(self, form):
        cart = Cart(self.request)
        if len(cart) == 0:
            return redirect('cart:cart_details')
        order = form.save(commit=False)
        order.user = self.request.user
        order.total_price = cart.get_total_price()
        order.save()
        products = Product.objects.filter(id__in=cart.cart.keys())
        orderitems = []
        for i in products:
            q = cart.cart[str(i.id)]['quantity']
            orderitems.append(
                OrderItem(order=order, product=i, quantity=q, total=q*i.price))
        OrderItem.objects.bulk_create(orderitems)
        cart.clear()
        messages.success(self.request, 'Your order is successfully placed.')
        return redirect('store:product_list')


class MyOrders(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'orders/order_list.html'
    context_object_name = 'orders'
    paginate_by = 20

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).annotate(total_items=Count('items'))


class OrderDetails(LoginRequiredMixin, generic.DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/order_details.html'

    def get_queryset(self, **kwargs):
        objs = super().get_queryset(**kwargs)
        return objs.filter(user=self.request.user).prefetch_related('items', 'items__product')


class OrderInvoice(LoginRequiredMixin, generic.DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/order_invoice.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related('items', 'items__product')

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        if obj.user_id == self.request.user.id or self.request.user.is_superuser:
            return obj
        raise Http404

2H-store-django/orders/templates/orders/order_details.html
{% extends 'base.html' %} {% load thumbnail %} {% block title %} Order no -
{{order.id}} {% endblock title %} {% block content %}
<h2 class="mt-4">Mã đặt - {{order.id}}</h2>
{% comment %}
<h4 class="font-weight-light">
  {{order.user.first_name|default:order.user.username}} {{order.user.last_name}}
</h4>
{% endcomment %}
<h4>
  {% if order.paid %}
  <span class="badge badge-success">Paid</span>
  {% else %}
  <span class="badge badge-danger">đang chờ thanh toán</span>
  {% endif %}
</h4>
<h5 class="font-weight-light">
  Địa chỉ thanh toán - {{order.address}}, {{order.city}}, {{order.pin_code}}
</h5>
<h5 class="font-weight-light">Trạng thái - {{order.status}}</h5>
<h5 class="font-weight-light">Thời gian - {{order.created}}</h5>
<h3 class="font-weight-light mt-4">Sản phẩm</h3>
<ul class="list-group shadow-sm">
  {% for o in order.items.all %}
  <li
    class="list-group-item d-flex align-items-center justify-content-between flex-column flex-md-row"
  >
    <div class="d-flex align-items-center">
      <img
        src="{% thumbnail o.product.image 75x0 %}"
        alt="{{o.product.name}}"
        class="img-fluid"
      />
      <h5 class="ml-3 mb-0 font-weight-light">
        <a href="{{o.product.get_absolute_url}}">{{o.product.name}}</a>
      </h5>
    </div>
    <h5 class="font-weight-light mb-0">
      {{o.product.price}}VNĐ * {{o.quantity}} = <b>{{o.total}}VNĐ</b>
    </h5>
  </li>
  {% endfor %}
  <li class="list-group-item bg-primary text-white">
    <h5 class="mb-0 text-right font-weight-light">
      Total - <b>{{order.total_price}}VNĐ</b>
    </h5>
  </li>
</ul>
<p class="my-2 text-center">
  <a href="{{order.get_absolute_url}}" class="btn btn-success">Hóa đơn</a>
</p>
{% endblock content %}

2H-store-django/orders/templates/orders/order_invoice.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Invoice Order - {{order.id}}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
  </head>
  <body>
    <div class="container my-4">
      <h2>Mã đặt - {{order.id}}</h2>
      <h4 class="mb-3">
        Tới - {{order.user.first_name|default:order.user.username}}
        {{order.user.last_name}}
      </h4>
      <h4 class="font-weight-light">{{order.address}}</h4>
      <h4 class="font-weight-light mb-3">{{order.city}}, {{order.pin_code}}</h4>
      <h5 class="font-weight-light mb-4">Placed on {{order.created}}</h5>
      <hr />
      <table class="table table-striped mt-4">
        <thead class="table-dark">
          <tr>
            <td>Tên </td>
            <td>Đơn giá</td>
            <td>Số lượng</td>
            <td>Tổng </td>
          </tr>
        </thead>
        <tbody>
          {% for o in order.items.all %}
          <tr>
            <td>{{o.product.name}}</td>
            <td>{{o.product.price}}VNĐ</td>
            <td>{{o.quantity}}</td>
            <td>{{o.total}}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td class="text-right">Tổng tiền -</td>
            <td>
              <b>{{order.total_price}}VNĐ</b>
            </td>
          </tr>
        </tfoot>
      </table>
      <h5>
        Trạng thái thanh toán - {% if order.paid %}
        <span class="badge badge-success">đã thanh toán</span>
        {% else %}
        <span class="badge badge-danger">Đang chờ thanh toán</span>
        {% endif %}
      </h5>
      <h5>Phương thức thanh toán - Thanh toán khi giao hàng</h5>
      <h5>Trạng thái - {{order.status}}</h5>
    </div>
    <footer class="text-center d-print-none">
      <button class="btn btn-primary" onclick="window.print()">In </button>
      <button class="btn btn-danger" onclick="history.back()">Trở lại</button>
    </footer>
  </body>
</html>

2H-store-django/orders/templates/orders/order_list.html
{% extends 'base.html' %} {% block title %}Your Orders {% endblock title %}
{% block content %}
<h1 class="font-weight-light mt-3">Your Orders</h1>
<hr />
<ul class="list-group my-3">
  {% for order in orders %}
  <li class="list-group-item">
    <h5 class="mb-2">
      {% if order.status == 'Delivered' %}
      <span class="badge badge-success font-weight-light">
        {{order.status}}
      </span>
      {% else %}
      <span class="badge badge-info font-weight-light">{{order.status}}</span>
      {% endif %}
    </h5>
    <h3>
      <a href="{% url 'orders:details' order.id %}">Order id - {{order.id}}</a>
    </h3>
    <h5>{{order.total_price}}VNĐ</h5>
    <p class="mb-0">{{order.total_items}} Items</p>
    <p class="mb-0">
      Delivery Address - {{order.address}}, {{order.city}}, {{order.pin_code}}
    </p>
    <p class="mb-0">Placed {{order.created|timesince}} ago.</p>
  </li>
  {% empty %}
  <li class="list-group-item text-center border-white">
    <h3 class="font-weight-light">You haven't placed any orders.</h3>
    <a href="{% url 'store:product_list' %}" class="btn btn-secondary">
      Continue Shopping
    </a>
  </li>
  {% endfor %}
</ul>
{% with page_obj as page %}
<p>Page <b>{{page.number}}</b> of <b>{{page.paginator.num_pages}}</b></p>
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a href="?page={{page.previous_page_number}}" class="page-link">
        Previous
      </a>
    </li>
    {% endif %}
    <li class="page-item active"><a href="#" class="page-link">1</a></li>
    {% if page.has_next %}
    <li class="page-item">
      <a href="?page={{page.next_page_number}}" class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endwith %} {% endblock content %}

2H-store-django/orders/templates/orders/place_order.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Place
Order {% endblock title %} {% block content %}
<div class="row my-3">
  <div class="col-md-6 col-12 mb-3">
    <div class="card">
      <h3 class="card-header mb-0">Order Summary</h3>
      <div class="card-body">
        {% for i in summary %}
        <p class="card-text d-flex justify-content-between mb-2">
          <span class="d-block"> {{i.quantity}} x {{i.product.name}} </span>
          <span class="d-block">Rs.{{i.total}}</span>
        </p>
        {% empty %}
        <h5 class="card-text font-weight-light">No items in cart.</h5>
        {% endfor %}
        <h4 class="card-text text-right">
          <span class="badge badge-primary">
            Grand Total - <b>{{cart.get_total_price}}VNĐ</b>
          </span>
        </h4>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-12">
    <div class="card card-body">
      <h3 class="mb-3">Shipping Details</h3>
      <form method="POST">
        {% csrf_token %} {{form|crispy}} {% if cart.empty %}
        <div class="alert alert-danger my-2">Your cart is empty.</div>
        <button disabled class="btn btn-success">Place Order</button>
        {% else %}
        <button type="submit" class="btn btn-success">Place Order</button>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock content %}